exports.APP_STORE = 'APP_STORE';
exports.ADD_TODO = 'ADD_TODO';
exports.EDIT_TODO = 'EDIT_TODO';
exports.REMOVE_TODO = 'REMOVE_TODO';
exports.TOGGLE_COMPLETED = 'TOGGLE_COMPLETED';
exports.TOGGLE_ALL_COMPLETED = 'TOGGLE_ALL_COMPLETED';
exports.CLEAR_COMPLETED = 'CLEAR_COMPLETED';
//# sourceMappingURL=StoreConsts.js.map